### ISSUE TITLE
offen: Fehlerausgabe bei falscher Spaltennummer

### ISSUE THREAD

**Issue by s50684** [Resiii99/4-Gewinnt#10]
Wenn eine falsche Spaltennummer als Input gegeben wird (zB 27), wird derzeit "nur" kein Spielstein gesetzt, es sollte jedoch eine Fehlermeldung mit Aufforderung zur korrekten neuen Eingabe durch denselben Spieler erfolgen.

**Comment by Resiii99** [comment]
Hinweis 'Bitte geben Sie  in der nächsten Runde eine Zahl zwischen 1 und {spiel.breite} ein!' wird nun gesetzt sobald input falsch ist, die aktuelle Runde hat der Spieler dann verschenkt, der andere Spieler spielt weiter.
