### ISSUE TITLE
offen: Fehlerausgabe bei voller Spalte

### ISSUE THREAD

**Issue by s50684** [Resiii99/4-Gewinnt#12]
Analog zur Fehlerausgabe bei falscher Spaltennummer sollte auch eine Fehlerausgabe mit anschließender Neuaufforderung zum Zug erfolgen, wenn eine Spalte bereits voll mit Spielsteinen ist.

**Comment by Resiii99** [comment]
Problem wurde bereits vor einigen Tagen bearbeitet - Spielzug wird durch falsche Spalteneingabe aber verschenkt.
